version: '3.8'

services:
  mongo:
    image: mongo
    container_name: job-portal-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: job-portal-server
    ports:
      - "5555:5555"
    depends_on:
      - mongo
    environment:
      -  MONGO_URL=mongodb://mongo:27017/job-portal
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: job-portal-client
    ports:
      - "5137:5137"
    tty: true
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo-data: